Fixed typing

diff --git a/.github/workflows/build_verification.yml b/.github/workflows/build_verification.yml
--- a/.github/workflows/build_verification.yml
+++ b/.github/workflows/build_verification.yml
@@ -2,22 +2,21 @@ name: Build Verification of Node.JS project
 
 on:
   push:
-    branches: [ main ]
+    branches: [main]
   pull_request:
-    types: [ opened, synchronize, reopened ]
+    types: [opened, synchronize, reopened]
 
 jobs:
   build:
-
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        node-version: [ 16.x, 18.X ]
+        node-version: [16.x, 18.X]
 
     steps:
       - uses: actions/checkout@v3
         with:
-          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
+          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
       - name: Set up Node.JS ${{ matrix.node-version }}
         uses: actions/setup-node@v3
         with:
@@ -51,22 +50,22 @@ jobs:
 
       - name: Test Report
         uses: dorny/test-reporter@v1
-        if: success() || failure()    # run this step even if previous step failed
+        if: success() || failure() # run this step even if previous step failed
         with:
-          name: JEST Tests            # Name of the check run which will be created
-          path: junit.xml             # Path to test results
-          reporter: jest-junit        # Format of test results
+          name: JEST Tests # Name of the check run which will be created
+          path: junit.xml # Path to test results
+          reporter: jest-junit # Format of test results
 
       - name: Save Code Linting Report JSON
-        run: npm run lint:report --if-present
+        run: npm run eslint --if-present
         continue-on-error: true
 
-#      - name: ESLint Annotate from Report JSON
-#        uses: ataylorme/eslint-annotate-action@1.2.0
-#        with:
-#          repo-token: ${{ secrets.SCM_TOKEN }}
-#          report-json: "eslint_report.json"
-#          only-pr-files: true
+      - name: ESLint Annotate from Report JSON
+        uses: ataylorme/eslint-annotate-action@1.2.0
+        with:
+          repo-token: ${{ secrets.SCM_TOKEN }}
+          report-json: 'eslint_report.json'
+          only-pr-files: true
 
       - name: Upload ESLint report
         uses: actions/upload-artifact@v2
